# **Análisis de Sentimientos**

**Objetivos:**

* Aplicar técnicas de análisis de sentimientos (métodos basados en reglas y aprendizaje automático).

* Implementar TextBlob para análisis de sentimientos.
* Utilizar el modelo de Naive Bayes para análisis de sentimientos.
* Desarrollar habilidades en la clasificación de texto.
* Representar datos textuales en vectores.
* Usar modelos supervisados para predecir el sentimiento.

**Stack:**

[![techs](https://skills.syvixor.com/api/icons?i=googlecolaboratory,python,numpy,pandas,seaborn,matplotlib,scikitlearn&perline=8&radius=40)](https://github.com/syvixor/skills-icons)

> Made with '\u{2665}' (♥) by Jesús Domínguez [@bluefeatherdev](https://github.com/bluefeatherdev)

## **Librerías necesarias**

In [1]:
from textblob import TextBlob
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

## **Actividad 1**

> Utiliza la librería TextBlob para analizar el sentimiento de varias frases. Debes interpretar el sentimiento de las frases como positivo, negativo o neutral en base a su polaridad.

### **Frases de entrenamiento del modelo**

1. "The weather today is absolutely beautiful!"

2. "I am really disappointed with the new update."
3. "The event was well-organized but lacked excitement."

### **Código en Python**

In [2]:
phrases = [
    "The weather today is absolutely beautiful!",
    "I am really disappointed with the new update.",
    "The event was well-organized but lacked excitement."
]

for phrase in phrases:
    analysis = TextBlob(phrase)
    polarity = analysis.sentiment.polarity

    sentiment = "Neutral"
    if polarity > 0:
        sentiment = "Positive"
    elif polarity < 0:
        sentiment = "Negative"

    print(f"Frase: '{phrase}'")
    print(f"Polaridad: {polarity}")
    print(f"Sentimiento: {sentiment}")
    print("-" * 30)

Frase: 'The weather today is absolutely beautiful!'
Polaridad: 1.0
Sentimiento: Positive
------------------------------
Frase: 'I am really disappointed with the new update.'
Polaridad: -0.3068181818181818
Sentimiento: Negative
------------------------------
Frase: 'The event was well-organized but lacked excitement.'
Polaridad: 0.0
Sentimiento: Neutral
------------------------------


## **Actividad 2**

> Entrena un modelo de clasificación de sentimientos utilizando Naive Bayes y
datos de ejemplo, y luego evalúa su precisión.

### **Frases de entrenamiento del modelo**

1. "This app is very intuitive!"

2. "I didn't enjoy the customer service."
3. "Quite average experience."
4. "Fantastic presentation!"
5. "The food was awful."

### **Código en Python**

#### **1. Preparar los datos**


> Crear listas para las frases de entrenamiento y sus sentimientos correspondientes.

In [3]:
training_phrases = [
    "This app is very intuitive!",
    "I didn't enjoy the customer service.",
    "Quite average experience.",
    "Fantastic presentation!",
    "The food was awful."
]

training_sentiments = [
    "positive",
    "negative",
    "neutral",
    "positive",
    "negative"
]

print("Training Phrases:")
for phrase, sentiment in zip(training_phrases, training_sentiments):
    print(f"'{phrase}' - {sentiment}")

Training Phrases:
'This app is very intuitive!' - positive
'I didn't enjoy the customer service.' - negative
'Quite average experience.' - neutral
'Fantastic presentation!' - positive
'The food was awful.' - negative


#### **2. Vectorizar el texto**


> Convertir las frases de texto en representaciones numéricas utilizando `CountVectorizer`.

In [4]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(training_phrases)

print("Document-Term Matrix (X):")
print(X.toarray())
print("\nVocabulary:")
print(vectorizer.get_feature_names_out())

Document-Term Matrix (X):
[[1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1]]

Vocabulary:
['app' 'average' 'awful' 'customer' 'didn' 'enjoy' 'experience'
 'fantastic' 'food' 'intuitive' 'is' 'presentation' 'quite' 'service'
 'the' 'this' 'very' 'was']


#### **3. Dividir los datos**

> Separar los datos en conjuntos de entrenamiento y prueba.

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, training_sentiments, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Length of y_train:", len(y_train))
print("Length of y_test:", len(y_test))

Shape of X_train: (4, 18)
Shape of X_test: (1, 18)
Length of y_train: 4
Length of y_test: 1


#### **4. Entrenar el modelo**


> Entrenar un modelo Naive Bayes (`MultinomialNB`) con los datos de entrenamiento.

In [6]:
model = MultinomialNB()
model.fit(X_train, y_train)

print("Model training complete.")

Model training complete.


#### **5. Evaluar el modelo**


> Predecir el sentimiento en el conjunto de prueba y calcular la precisión del modelo.

In [7]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"Predicted sentiments for the test set: {y_pred}")
print(f"Actual sentiments for the test set: {y_test}")
print(f"Accuracy of the Naive Bayes model: {accuracy}")

Predicted sentiments for the test set: ['negative']
Actual sentiments for the test set: ['negative']
Accuracy of the Naive Bayes model: 1.0


## **Conclusiones**


> 1. Se analizó el sentimiento de frases usando TextBlob (basado en reglas).
>
> 1. Se entrenó un modelo Naive Bayes con datos de ejemplo.
> 1. Los datos de texto se vectorizaron para el modelo.
> 1. El modelo Naive Bayes predijo correctamente el sentimiento en el conjunto de prueba pequeño.
> 1. La alta precisión se debe al conjunto de datos limitado y simple.
> 1. Se necesita un conjunto de datos más grande y diverso para un modelo robusto.

> Made with '\u{2665}' (♥) by Jesús Domínguez [@bluefeatherdev](https://github.com/bluefeatherdev)